version: '3.7'

services:
  database-ignite-challenge:
    image: postgres
    container_name: pg-ignite-challenge
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=queries_challenge
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
